spring.application.name=DevSync
spring.datasource.url=jdbc:postgresql://localhost:5432/devsync
spring.datasource.username=altafhussain
spring.datasource.password=altaf@786

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=8jN8J8fDqP7cB2VhW1mK9LxQ4rZ7nTaDSOUYB98efwecE5sFpHg=